"""added new fields for v1.0.0

Revision ID: 5230ecdd25e9
Revises: 1fdf20deafd0
Create Date: 2026-08-17 06:23:06.019439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5230ecdd25e9'
down_revision: Union[str, Sequence[str], None] = '1fdf20deafd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
