name: Docker containers checks

on:
  push:
    branches: [ "main", "v1-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      
    - name: Run docker compose
      run: |
        docker compose --profile test up -d --build
        sleep 20
      env:
        TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
        TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
        TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
        TEST_POSTGRES_URL: ${{ secrets.TEST_POSTGRES_URL }}

    - name: Show API logs
      run: |
        docker logs testprism --tail 50
        
    - name: Check container is running
      run: |
        docker ps | grep testprism